"""initial schema

Revision ID: 7bfc63565574
Revises: 
Create Date: 2026-08-13 23:07:14.714679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bfc63565574'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_users_email', ['email'], unique=False)

    op.create_table('hosted_zones',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('comment', sa.String(), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("type IN ('PUBLIC', 'PRIVATE')", name='ck_zone_type'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('created_by', 'name', 'type', name='uq_user_zone_name_type')
    )
    with op.batch_alter_table('hosted_zones', schema=None) as batch_op:
        batch_op.create_index('idx_zones_created_by', ['created_by'], unique=False)
        batch_op.create_index('idx_zones_name', ['name'], unique=False)

    op.create_table('user_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index('idx_sessions_token', ['token'], unique=False)
        batch_op.create_index('idx_sessions_user', ['user_id'], unique=False)

    op.create_table('dns_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('hosted_zone_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('ttl', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('routing_policy', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hosted_zone_id'], ['hosted_zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dns_records', schema=None) as batch_op:
        batch_op.create_index('idx_records_name', ['name'], unique=False)
        batch_op.create_index('idx_records_type', ['type'], unique=False)
        batch_op.create_index('idx_records_zone', ['hosted_zone_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dns_records', schema=None) as batch_op:
        batch_op.drop_index('idx_records_zone')
        batch_op.drop_index('idx_records_type')
        batch_op.drop_index('idx_records_name')

    op.drop_table('dns_records')
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index('idx_sessions_user')
        batch_op.drop_index('idx_sessions_token')

    op.drop_table('user_sessions')
    with op.batch_alter_table('hosted_zones', schema=None) as batch_op:
        batch_op.drop_index('idx_zones_name')
        batch_op.drop_index('idx_zones_created_by')

    op.drop_table('hosted_zones')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('idx_users_email')

    op.drop_table('users')
    # ### end Alembic commands ###
